### ISSUE TITLE
Use assert(false) do prevent nullifier usage if it's not intended

### ISSUE THREAD

**Issue by spalladino** [defi-wonderland/aztec-private-oracle#1]
Instead of emitting zero, `assert(false)`. See [here](https://github.com/AztecProtocol/aztec-packages/blob/a6b4bee68cad685d77b5346e3efc038929428b63/yarn-project/noir-contracts/src/contracts/docs_example_contract/src/types/profile_note.nr#L42-L45) for an example.

https://github.com/defi-wonderland/aztec-private-oracle/blob/afe8cb4e3bc34219f925859790be56c79fb0188c/src/types/answer_note.nr#L52-L55

**Comment by 0xShaito** [comment]
https://github.com/defi-wonderland/aztec-private-oracle/commit/56b0cfd31bdb8ece4287816657118b8e6583940f

**Comment by simon-something** [comment]
I've reverted this change: unlike in the example, we emit encrypted log and therefore need `compute_nullifier` for `compute_note_hash_and_nullifier`, even if we don't nullify (if not, this happens when emitting:
<img width="1180" alt="image" src="https://github.com/defi-wonderland/aztec-private-oracle/assets/83670532/112f61c7-a907-4d39-8e02-99aba52a65f9">)

@0xShaito @spalladino
